---
server:
  port: 8082
  error:
    include-message: always

spring:
  application:
    name: epothon-backend
  profiles:
    active: pgsql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update


logging:
  level:
    root: INFO
---

---

### PgSQL profile

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/epothonDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}
  config:
    activate:
      on-profile:  pgsql

---
